[workspace]
resolver = "2"
members = [
    "clients/rust-cartridge",
    "clients/rust-ghost",
    "clients/rust-legit",
    "programs/bgl-cartridge",
    "programs/bgl-ghost",
    "programs/bgl-legit"
]
